### ISSUE TITLE
bench error 

### ISSUE THREAD

**Issue by mohamedatef1234** [LesnyRumcajs/grpc_bench#106]
Hello, 
i am trying to benchmark the rust tonic st, i am stucked here when i am trying to bench, i build it normally
https://user-images.githubusercontent.com/78416011/108701090-2c69f480-7510-11eb-85dd-fbe98542c73e.png
i havn't made any modification on the bench or build scripts
but i have added the copy command for payload to the docker file
https://user-images.githubusercontent.com/78416011/108701290-6935eb80-7510-11eb-8c66-875642a7b3be.png

**Comment by LesnyRumcajs** [comment]
Hi @mohamedatef1234 
Unfortunately it seems you're running the benchmark on Windows and the `${PWD}` gets translated into your Git application directory instead of repository root - you may try to replace it locally with absolute path but some others issues may arise.

All in all, the prerequisite for running those benchmarks locally is Linux or MacOS. You may have some luck running it in WSL / WSL2 or a hand-made virtualized environment with e.g. VirtualBox and Ubuntu.
