### ISSUE TITLE
Make benchmark more realistic

### ISSUE THREAD

**Issue by JamesNK** [LesnyRumcajs/grpc_bench#120]
The current results aren't realistic because the method on the server does no work. In the real-world there will be I/O (reading from FS, DB, calling another service, etc) and an execution model that assumes no blocking will grind to a halt.

Consider either:
1. Simulating work on the server by adding a delay. For example, the method waits 50ms before sending a response. In .NET that would look something like this:
```cs
public async Task<HelloReply> Hello(HelloRequest request, ServerCallContext context)
{
    await Task.Delay(50);
    return new HelloReply { Message = request.Name };
}
```
2. Or having rules about implementation requirements. I don't know if you're familiar with TechEmpower benchmarks but they have rules about how implementations are written and behave.

**Comment by Trisfald** [comment]
I kind of agree with @JamesNK , the benchmarks should take into account the fact there will be work to do for each request.

What we can (quickly) do is to add a ENV variable `GRPC_.SERVER_TASK_SLEEP` that if set to a non zero value will trigger a sleep in the server's request handler

**Comment by LesnyRumcajs** [comment]
Yes, this definitely makes sense. Going into details, I'm not sure if a raw sleep is going to achieve our goals - basically simulate an actual workload, right? I would imagine it could be achieved by doing a barbaric loop, something along the lines of:
```
start = Time.now()
while Time.now() < start + workload_time do
  # Nothing, just stealing CPU cycles
end
```

What do you guys think?

**Comment by JamesNK** [comment]
Most I/O tasks use zero CPU. For example, a gRPC call executing on a server is doing nothing while waiting for the result from a database to come back.

A delay with no CPU usage is perfectly fine to stress a gRPC server with concurrency.

**Comment by LesnyRumcajs** [comment]
@JamesNK sounds good, we could parametrize it as @Trisfald suggested to make it optional and all should be fine, we can merge directly to master.

**Comment by JamesNK** [comment]
Something else to consider is the client. The number of connections and streams will need to be increased because there will be more concurrent calls happening.

https://github.com/LesnyRumcajs/grpc_bench/blob/d4bc0e311a97a6b18858bf2223e45f90d05fc14a/bench.sh#L12-L13

The number of connections will need to increase. Perhaps to 50, or 100. I don't know at what point the client would stop being a bottleneck.

**Comment by mike-barber** [comment]
It's a tricky one to implement, or at least implement consistently across various languages.

A delay or a busy loop is prone to timing error, and the solution that happens to have the shortest elapsed time per iteration will probably win. 

We're dealing with pretty short times here: typically less than a millisecond. I'm guessing the time in the delay will be the dominant factor, and we'd only be measuring how accurately each language/framework can do a delay rather than anything related to GRPC. I could be wrong though :)

**Comment by JamesNK** [comment]
If you want to measure latency then adding artificial latency doesn't make sense. The reason to do it would be to benchmark throughput - requests per second - under high concurrency.

Hmm, I wonder if an alternative option here is just increasing the number of connections each client makes. 50 connections * 50 concurrent streams * multiple client VMs is a lot of requests. I don't know if that would work or not. It seems like the clients are struggling to keep up with the fastest servers.

**Comment by mike-barber** [comment]
Agreed, with this sort of load it's a big issue for client. It's taking way more CPU cycles than the servers it's testing, partly because the servers don't have much work to do.

**Comment by mike-barber** [comment]
James, what you've said makes a lot of sense, and I can see where you're coming from. 

It's going to be interesting figuring out how to get `ghz` to do what we want it to. Currently, I think it's throttling itself by waiting for responses before sending further requests. As a result, I still think it might be important to standardise the "delay" each server introduces before responding, because of the above throttling behaviour. Servers with shorter delays will result in higher measured throughput, all things being equal. 

Maybe it would make sense to have each server call out to *another* standardised service (on grpc or http for instance) that responds with a very well controlled delay, in order to get consistent delay performance.

**Comment by JamesNK** [comment]
ghz has pretty good docs about how it works:

https://ghz.sh/docs/options#-c---concurrency
https://ghz.sh/docs/options#--connections

So it isn't `concurrency * connections` like I thought. It is `concurrency`, with that number divided up between connections.

What I suggest is increasing the concurrency number to 250 and connections to 10. 25 concurrent requests per connection is fine. It's a quarter of the 100 that maximum most servers allow by default.

> Maybe it would make sense to have each server call out to another standardised service (on grpc or http for instance) that responds with a very well controlled delay, in order to get consistent delay performance.

That would mix in the performance of how well each implementation can make HTTP or gRPC calls with serving gRPC requests. Its not a bad thing to measure, but these tests seem focused on the server.

**Comment by Trisfald** [comment]
@JamesNK I'll try to run the tests with the configuration you suggested 👍

**Comment by mike-barber** [comment]
There's also the `--async` option that looks potentially interesting, although might need to be combined with a load schedule or `--rps` limit by the sounds of it. 

We could work out the sensitivity of the results to the delay length by altering the delay within a single server (e.g. test at 50ms and 55ms).
