### ISSUE TITLE
Cache the images

### ISSUE THREAD

**Issue by LesnyRumcajs** [LesnyRumcajs/grpc_bench#64]
The build-images step takes annoyingly long (e.g. for Lua that needs to build the entire gRPC library). We should to devise a strategy to cache the built images / don't build them at each run if there were no changes. Any ideas?

**Comment by Trisfald** [comment]
On the perf machine it's not so bad because I never remove them and docker can work its magic.

Generally speaking, the first idea that comes to my mind is to open an account on docker hub and push everything? Not sure how it will help the CI though, in theory it should build and push everything every time.

**Comment by LesnyRumcajs** [comment]
Yes, me as well, locally it's totally fine. Perhaps this technology or similar could be used https://github.com/marketplace/actions/build-docker-images-using-cache

**Comment by Trisfald** [comment]
> Yes, me as well, locally it's totally fine. Perhaps this technology or similar could be used https://github.com/marketplace/actions/build-docker-images-using-cache

looks good!
